export const SERVICE_CREATE_REQUEST = "SERVICE_CREATE_REQUEST";
export const SERVICE_CREATE_SUCCESS = "SERVICE_CREATE_SUCCESS";
export const SERVICE_CREATE_FAIL = "SERVICE_CREATE_FAIL";
export const SERVICE_CREATE_RESET = "SERVICE_CREATE_RESET";

export const SERVICE_DETAILS_REQUEST = "SERVICE_DETAILS_REQUEST";
export const SERVICE_DETAILS_SUCCESS = "SERVICE_DETAILS_SUCCESS";
export const SERVICE_DETAILS_FAIL = "SERVICE_DETAILS_FAIL";

export const SERVICE_PAY_REQUEST = "SERVICE_PAY_REQUEST";
export const SERVICE_PAY_SUCCESS = "SERVICE_PAY_SUCCESS";
export const SERVICE_PAY_FAIL = "SERVICE_PAY_FAIL";
export const SERVICE_PAY_RESET = "SERVICE_PAY_RESET";

export const SERVICE_MINE_REQUEST = "SERVICE_MINE_REQUEST";
export const SERVICE_MINE_SUCCESS = "SERVICE_MINE_SUCCESS";
export const SERVICE_MINE_FAIL = "SERVICE_MINE_FAIL";

// Cart Constants

export const SERVICE_CART_ADD_ITEM = "SERVICE_CART_ADD_ITEM";
export const SERVICE_CART_REMOVE_ITEM = "SERVICE_CART_REMOVE_ITEM";

export const SERVICE_CART_SAVE_SHIPPING_ADDRESS = "SERVICE_CART_SAVE_SHIPPING_ADDRESS";
export const SERVICE_CART_SAVE_PAYMENT_METHOD = "SERVICE_CART_SAVE_PAYMENT_METHOD";

export const SERVICE_CART_EMPTY = "SERVICE_CART_EMPTY";