// User Signin Constants
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

// User Registration Constants
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// User Details Constants
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// User Update Profile Constants
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

// Vendor Registration Constants
export const VENDOR_REGISTER_REQUEST = "VENDOR_REGISTER_REQUEST";
export const VENDOR_REGISTER_SUCCESS = "VENDOR_REGISTER_SUCCESS";
export const VENDOR_REGISTER_FAIL = "VENDOR_REGISTER_FAIL";

export const VENDOR_DETAILS_REQUEST = "VENDOR_DETAILS_REQUEST";
export const VENDOR_DETAILS_SUCCESS = "VENDOR_DETAILS_SUCCESS";
export const VENDOR_DETAILS_FAIL = "VENDOR_DETAILS_FAIL";

export const VENDOR_SIGNIN_REQUEST = "VENDOR_SIGNIN_REQUEST";
export const VENDOR_SIGNIN_SUCCESS = "VENDOR_SIGNIN_SUCCESS";
export const VENDOR_SIGNIN_FAIL = "VENDOR_SIGNIN_FAIL";
export const VENDOR_SIGNOUT = "VENDOR_SIGNOUT";

export const VENDOR_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
// User Update Profile Constants
export const VENDOR_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const VENDOR_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";
export const VENDOR_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";



// DELIVERY Registration Constants
export const DELIVERY_REGISTER_REQUEST = "DELIVERY_REGISTER_REQUEST";
export const DELIVERY_REGISTER_SUCCESS = "DELIVERY_REGISTER_SUCCESS";
export const DELIVERY_REGISTER_FAIL = "DELIVERY_REGISTER_FAIL";

export const DELIVERY_DETAILS_REQUEST = "DELIVERY_DETAILS_REQUEST";
export const DELIVERY_DETAILS_SUCCESS = "DELIVERY_DETAILS_SUCCESS";
export const DELIVERY_DETAILS_FAIL = "DELIVERY_DETAILS_FAIL";

export const DELIVERY_SIGNIN_REQUEST = "DELIVERY_SIGNIN_REQUEST";
export const DELIVERY_SIGNIN_SUCCESS = "DELIVERY_SIGNIN_SUCCESS";
export const DELIVERY_SIGNIN_FAIL = "DELIVERY_SIGNIN_FAIL";
export const DELIVERY_SIGNOUT = "DELIVERY_SIGNOUT";

export const DELIVERY_UPDATE_PROFILE_REQUEST = "DELIVERY_UPDATE_PROFILE_REQUEST";
export const DELIVERY_UPDATE_PROFILE_SUCCESS = "DELIVERY_UPDATE_PROFILE_SUCCESS";
export const DELIVERY_UPDATE_PROFILE_RESET = "DELIVERY_UPDATE_PROFILE_RESET";
export const DELIVERY_UPDATE_PROFILE_FAIL = "DELIVERY_UPDATE_PROFILE_FAIL";
